prestashop:
  container_name: hipay-professional-shop-ps17
  build: .
  ports:
    - "8086:80"
  links:
    - smtp
  env_file:
    - env
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-professional-ps17
  ports:
    - "1086:1080"
